#!/bin/sh
#
#  Copyright 2014 Alcatel-Lucent Enterprise.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
#  except in compliance with the License. You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software distributed under the License
#  is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
#  either express or implied. See the License for the specific language governing permissions
#  and limitations under the License.
#
#
# $File: omniswitch_setup$
# $Build: OONP_I_R01_6$
# $Date: 01/02/2015 13:08:27$
# Author: vapoonat
#
#

# This is a shell script to do initial configuration on the OmniSwitches
# for the OmniSwitch Neutron plug-in to use. It uses the device details
# and other configuration options from the plug-in configuration file

python omniswitch_topology_utils.py setup_initial $1
